title = "Rakan A. Alseghayer"
baseURL = "http://www.alseghayer.com/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Rakan A. Alseghayer"
  description = "Rakan Alseghayer's portfolio webpage."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = " Rakan Alseghayer Â© 2022"
    url = "http://www.alseghayer.com/"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/rakan-alseghayer"
  [[params.socialIcons]]
    icon = "fa fa-graduation-cap"
    title = "Google Scholar"
    url = "https://scholar.google.com/citations?user=k0mh_XUAAAAJ&hl=en"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:ralseghayer@cs.pitt.edu"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/r_alseghayer"


[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
   weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 4

  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 5

  [[menu.main]]
    name = "Testimonies"
    url = "/testimonies"
    weight = 6

  [[menu.main]]
    name = "Awards"
    url = "/awards"
    weight = 7

  [[menu.main]]
    name = "Service"
    url = "/service"
    weight = 8

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 9


[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
